services:
  redis:
    image: "redis"
    restart: unless-stopped
    command: >-
      redis-server
      --save 60 1
      --loglevel notice
    volumes:
      - "./data/redis/rdata:/data"
  red:
    image: "ghcr.io/steffo99/todocolors-red"
    restart: unless-stopped
    environment:
      REDIS_CONN: "redis://redis:6379/"  # You probably don't need to change this
      AXUM_XFORWARDED: "TODO-YOUR-PUBLIC-URL-GOES-HERE"
      TODORED_RATE_LIMIT_CONNECTIONS_PER_MINUTE: 5
      TODORED_RATE_LIMIT_MESSAGES_PER_MINUTE: 100
  blue:
    image: "ghcr.io/steffo99/todocolors-blue"
    restart: unless-stopped
  caddy:
    image: "caddy"
    restart: unless-stopped
    volumes:
      - "./data/caddy:/data"
      - "./config/caddy/Caddyfile:/etc/caddy/Caddyfile"
    network_mode: host
